import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "VivaTrip — Full Stack Travel SaaS", description: "Case study of VivaTrip, a full-stack travel planning product built with Next.js, React, TypeScript, Supabase, PostgreSQL and secure SSR authentication." };
const features = [["Secure authentication", "SSR authentication with protected routes, cookie-based sessions and password recovery flows."],["Saved trip context", "Trip data feeds planning screens directly, reducing duplicate information and keeping the experience consistent."],["Pre-trip planning", "Checklist-driven preparation designed around the actual destination and travel context."],["Scalable product foundation", "Structured to grow into itinerary editing, destination discovery, alerts and paid travel-planning features."]];
const technicalHighlights = ["Next.js App Router with protected routes","Supabase authentication and persistent sessions","Server-side auth checks for private screens","Reusable trip and profile UI components","Responsive layouts for desktop and mobile","Production deployment with Vercel"];

export default function VivaTripProjectPage() { return <main className="min-h-screen bg-[#24194f] text-white">
<section className="border-b border-white/10 bg-gradient-to-b from-[#5748b9] via-[#3c2f86] to-[#291f62]"><div className="mx-auto max-w-7xl px-6 pb-24 pt-8 md:px-10 md:pb-36"><div className="flex justify-between"><Link href="/#work" className="text-xs uppercase tracking-[0.24em] text-white/65">← Back to work</Link><span className="text-xs uppercase tracking-[0.24em] text-white/45">Case study · 02</span></div><div className="mt-24 grid gap-14 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><p className="text-xs uppercase tracking-[0.32em] text-[#d7cdf2]/60">Travel SaaS / Full stack</p><h1 className="mt-6 text-6xl font-medium tracking-[-0.06em] md:text-8xl">VivaTrip</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#ddd5f3]/75">A full-stack travel product that brings authentication, saved trips, itinerary workflows and pre-travel preparation into one connected experience.</p><div className="mt-9 flex flex-wrap gap-3"><a href="https://vivatrip.vercel.app" target="_blank" rel="noreferrer" className="rounded-full bg-white px-5 py-3 text-sm font-medium text-[#2d2168]">Live product ↗</a><a href="https://github.com/brenfreitas29/VivaTrip" target="_blank" rel="noreferrer" className="rounded-full border border-white/20 px-5 py-3 text-sm text-white/80">View code ↗</a></div></div><div className="rounded-[2rem] border border-white/15 bg-[#281d61]/60 p-4 md:p-6"><div className="relative aspect-[1886/883] overflow-hidden rounded-[1.4rem] bg-white"><div className="pointer-events-none absolute inset-0 overflow-hidden"><iframe src="https://vivatrip.vercel.app" title="VivaTrip homepage live preview" loading="eager" tabIndex={-1} className="absolute left-0 top-0 h-[918px] w-[1920px] origin-top-left border-0" style={{ transform: "scale(0.42)", transformOrigin: "top left" }} /></div></div></div></div></div></section>
<section className="bg-gradient-to-b from-[#291f62] to-[#40318b]"><div className="mx-auto max-w-7xl px-6 py-28 md:px-10"><div className="grid gap-12 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="text-xs uppercase tracking-[0.32em] text-[#d7cdf2]/60">The challenge</p><h2 className="mt-5 text-4xl font-medium tracking-[-0.04em] md:text-5xl">Travel information is fragmented. The product should not be.</h2></div><div className="grid gap-6 sm:grid-cols-2">{features.map(([title,text])=><article key={title} className="border-t border-white/15 pt-6"><h3 className="text-lg font-medium">{title}</h3><p className="mt-3 text-sm leading-7 text-[#ddd5f3]/68">{text}</p></article>)}</div></div></div></section>
<section className="border-t border-white/10 bg-[#31236f]"><div className="mx-auto grid max-w-7xl gap-12 px-6 py-28 md:px-10 lg:grid-cols-2"><div><p className="text-xs uppercase tracking-[0.3em] text-[#d7cdf2]/60">Technical highlights</p><h2 className="mt-5 text-4xl font-medium tracking-[-0.04em] md:text-5xl">Built as a real product, not a static concept.</h2></div><div className="divide-y divide-white/10 border-y border-white/10">{technicalHighlights.map(item=><p key={item} className="py-4 text-sm text-white/75">{item}</p>)}</div></div></section>
<section className="border-t border-white/10 bg-gradient-to-b from-[#31236f] to-[#3b2b82]"><div className="mx-auto max-w-7xl px-6 py-28 md:px-10"><p className="text-xs uppercase tracking-[0.3em] text-[#d7cdf2]/60">Engineering reflection</p><h2 className="mt-5 max-w-3xl text-4xl font-medium tracking-[-0.04em] md:text-5xl">Hard parts, decisions and next steps.</h2><div className="mt-12 grid gap-8 md:grid-cols-3"><article className="border-t border-white/15 pt-6"><p className="text-xs uppercase tracking-[0.2em] text-[#f0a6da]">Technical challenge</p><h3 className="mt-4 text-xl font-medium">Keeping authentication secure across routes</h3><p className="mt-4 text-sm leading-7 text-white/65">The product needed private trip and profile screens without relying only on client-side redirects. The solution uses server-side session checks and protected routing so authentication is part of the application architecture.</p></article><article className="border-t border-white/15 pt-6"><p className="text-xs uppercase tracking-[0.2em] text-[#f0a6da]">What I learned</p><h3 className="mt-4 text-xl font-medium">Context should have one source of truth</h3><p className="mt-4 text-sm leading-7 text-white/65">Saved trip data now drives destination-aware preparation instead of asking users to repeat the same information. This reinforced how data modeling directly affects UX quality.</p></article><article className="border-t border-white/15 pt-6"><p className="text-xs uppercase tracking-[0.2em] text-[#f0a6da]">What I would improve</p><h3 className="mt-4 text-xl font-medium">More automated coverage for critical flows</h3><p className="mt-4 text-sm leading-7 text-white/65">The next engineering step is stronger end-to-end coverage for authentication, trip creation and itinerary flows, plus more resilient loading and error states.</p></article></div></div></section>
<section className="border-t border-white/10 bg-[#362776]"><div className="mx-auto max-w-7xl px-6 py-24 md:px-10"><p className="text-xs uppercase tracking-[0.3em] text-[#d7cdf2]/60">Stack</p><div className="mt-6 flex flex-wrap gap-3">{["Next.js","React","TypeScript","Supabase","PostgreSQL","SSR Auth","Responsive UI","Vercel"].map(x=><span key={x} className="rounded-full border border-white/15 px-4 py-2 text-sm text-white/75">{x}</span>)}</div></div></section>
</main>; }
