import StudioHero from "@/components/StudioHero";
import ProjectCard from "@/components/ProjectCard";
import SkillsSection from "@/components/SkillsSection";
import Magnetic from "@/components/Magnetic";
import SideAtmosphere from "@/components/SideAtmosphere";
import ScrollJourney from "@/components/ScrollJourney";

const projects = [
  { number: "01", title: "FlowDesk", category: "FEATURED · AI SAAS / CRM", description: "Multi-tenant CRM for real business workflows — leads, Kanban pipeline, conversations, scheduling, automation, analytics and subscription-ready architecture.", tags: ["Next.js", "TypeScript", "Supabase", "Stripe", "RLS", "AI Automation"], image: "/projects/flowdesk-dashboard.jpg", previewUrl: "https://whats-app-crm-system-architecture.vercel.app", href: "/projects/flowdesk", liveUrl: "https://whats-app-crm-system-architecture.vercel.app", codeUrl: "https://github.com/brenfreitas29/FlowDesk" },
  { number: "02", title: "VivaTrip", category: "FEATURED · TRAVEL PRODUCT", description: "Full-stack travel product combining flight discovery, cash-versus-miles comparison, protected user flows and affiliate-ready booking experiences.", tags: ["Next.js", "React", "TypeScript", "Supabase", "SSR Auth", "Travel Tech"], image: "/projects/vivatrip-portfolio.jpg", previewUrl: "https://vivatrip.vercel.app", href: "/projects/vivatrip", liveUrl: "https://vivatrip.vercel.app", codeUrl: "https://github.com/brenfreitas29/VivaTrip" },
  { number: "03", title: "Hair & Skin Clinic", category: "BUSINESS WEBSITE / UX", description: "Responsive multilingual clinic experience built around credibility, clear service discovery and conversion-focused user journeys.", tags: ["Next.js", "React", "TypeScript", "Responsive UI", "Multilingual"], image: "/projects/hair-skin-clinic.png", href: "/projects/hair-skin-clinic", liveUrl: "https://graftclinic.vercel.app", codeUrl: "https://github.com/brenfreitas29/graftclinic" },
];
const capabilities = [["01","SaaS products","Authentication, multi-tenant data, dashboards, subscriptions and production deployment."],["02","AI automation","AI-enabled workflows and API integrations that connect product and business operations."],["03","Full-stack apps","Responsive React interfaces backed by application logic, data and secure user flows."],["04","Product engineering","Features, UX refinement and stronger technical foundations for products already in motion."]];

export default function Home(){return <main className="min-h-screen overflow-hidden bg-[#100b24] text-white"><SideAtmosphere/><ScrollJourney/><StudioHero/>
<section id="work" className="relative overflow-hidden border-t border-white/[.07] bg-gradient-to-b from-[#17102f]/98 via-[#130d2a]/98 to-[#100b24] px-6 py-20 md:px-10 md:py-28"><div className="pointer-events-none absolute left-[8%] top-10 h-[420px] w-[420px] rounded-full bg-[#8067d9]/12 blur-[150px]"/><div className="pointer-events-none absolute right-[5%] top-[42%] h-[360px] w-[360px] rounded-full bg-[#efb7df]/[.055] blur-[160px]"/><div className="relative z-10 mx-auto max-w-[1450px]"><div className="mb-14 grid gap-8 lg:grid-cols-[.65fr_1.35fr] lg:items-end md:mb-18"><p className="text-xs uppercase tracking-[.38em] text-[#cfc3f5]/48">Selected work · 2026</p><div><h2 className="max-w-5xl text-5xl font-medium leading-[.96] tracking-[-.055em] md:text-7xl lg:text-[5.5rem]">Products with design on the surface.<span className="block font-normal italic text-[#efb7df]">Engineering underneath.</span></h2><p className="mt-6 max-w-2xl text-base leading-7 text-[#cfc3f5]/58">Live products across SaaS, travel tech and business platforms — built with real authentication, databases, integrations and deployment.</p></div></div><div className="flex flex-col gap-10 md:gap-14">{projects.map(project=><ProjectCard key={project.number} project={project}/>)}</div></div></section>
<section className="relative border-t border-white/[.07] bg-[#100b24] px-6 py-24 md:px-10 md:py-32"><div className="pointer-events-none absolute left-1/2 top-0 h-[420px] w-[55vw] -translate-x-1/2 bg-[#7457ff]/[.045] blur-[160px]"/><div className="relative mx-auto max-w-[1450px]"><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr] lg:gap-20"><div className="lg:sticky lg:top-24 lg:self-start"><p className="text-xs uppercase tracking-[.35em] text-[#cfc3f5]/45">Capabilities</p><h2 className="mt-6 text-5xl font-medium leading-[.98] tracking-[-.055em] md:text-6xl">From idea to<span className="block font-normal italic text-[#efb7df]">working product.</span></h2><p className="mt-6 max-w-md text-base leading-8 text-[#cfc3f5]/55">I work across interface, application logic and data to turn business requirements into software people can actually use.</p></div><div>{capabilities.map(([n,t,d])=><article key={t} className="group grid gap-4 border-t border-white/[.09] py-8 sm:grid-cols-[70px_1fr]"><span className="text-xs tracking-[.18em] text-[#cfc3f5]/28">{n}</span><div><h3 className="text-2xl font-medium text-white transition group-hover:text-[#efb7df] md:text-3xl">{t}</h3><p className="mt-3 max-w-xl text-sm leading-7 text-[#cfc3f5]/52">{d}</p></div></article>)}</div></div></div></section>
<SkillsSection/>
<section id="about" className="relative overflow-hidden border-t border-white/[.07] bg-[#130d2a] px-6 py-24 md:px-10 md:py-28"><div className="pointer-events-none absolute -right-20 top-1/2 h-[420px] w-[420px] -translate-y-1/2 rounded-full bg-[#8b6bd8]/[.08] blur-[150px]"/><div className="relative z-10 mx-auto max-w-[1450px]"><div className="grid gap-8 lg:grid-cols-[.58fr_1.42fr] lg:gap-20"><div><p className="text-xs uppercase tracking-[.35em] text-[#cfc3f5]/38">About / Availability</p><p className="mt-7 max-w-xs text-sm leading-7 text-[#cfc3f5]/45">Full Stack · Frontend · SaaS · AI Automation · Remote</p></div><div><h2 className="max-w-5xl text-5xl font-medium leading-[.94] tracking-[-.055em] md:text-7xl">I like turning messy ideas into<span className="block font-normal italic text-[#efb7df]">clear, usable products.</span></h2><div className="mt-10 grid gap-5 md:grid-cols-2"><div className="rounded-[1.4rem] border border-white/[.09] bg-[#1d1640]/70 p-6"><p className="text-[10px] uppercase tracking-[.22em] text-[#cfc3f5]/35">What I build</p><p className="mt-4 text-base leading-7 text-[#cfc3f5]/62">Modern SaaS products, web applications and AI-enabled workflows with a strong focus on usability and visual identity.</p></div><div className="rounded-[1.4rem] border border-white/[.09] bg-[#1d1640]/70 p-6"><p className="text-[10px] uppercase tracking-[.22em] text-[#cfc3f5]/35">Open to</p><p className="mt-4 text-base leading-7 text-[#cfc3f5]/62">Remote Full Stack, Frontend and product-focused roles, plus selected freelance product work.</p></div></div><div className="mt-8 flex flex-wrap gap-3"><a href="/resume" className="rounded-full bg-white px-6 py-3 text-sm font-medium text-[#1b1238]">View resume ↗</a><a href="https://github.com/brenfreitas29" target="_blank" rel="noopener noreferrer" className="rounded-full border border-white/15 px-6 py-3 text-sm text-[#cfc3f5]/75">GitHub ↗</a></div></div></div></div></section>
<section id="contact" className="relative overflow-hidden border-t border-white/[.07] bg-[#0d081d]"><div className="absolute left-1/2 top-1/2 h-[700px] w-[700px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#7457ff]/[.09] blur-[190px]"/><div className="absolute left-[7%] top-[18%] hidden h-32 w-32 rounded-full border border-[#cfc3f5]/10 lg:block"/><div className="absolute right-[8%] bottom-[18%] hidden h-48 w-72 rotate-[-12deg] rounded-[50%] border border-dashed border-[#efb7df]/15 lg:block"/><div className="relative z-10 mx-auto max-w-[1450px] px-6 py-28 md:px-10 md:py-36"><div className="grid items-end gap-12 lg:grid-cols-[1.15fr_.85fr]"><div><p className="mb-7 text-xs uppercase tracking-[.35em] text-[#cfc3f5]/45">Next collaboration</p><h2 className="max-w-5xl text-6xl font-semibold leading-[.86] tracking-[-.07em] md:text-8xl lg:text-[8rem]">Let&apos;s make<span className="block font-normal italic text-[#efb7df]">the next one.</span></h2></div><div className="lg:pb-4"><p className="max-w-md text-base leading-8 text-[#cfc3f5]/58">SaaS · Full Stack · Frontend · AI Automation. From the first interface to production deployment.</p><div className="mt-8 flex flex-wrap gap-3"><Magnetic strength={.3}><a href="/start-a-project" className="inline-flex rounded-full bg-white px-8 py-4 text-sm font-semibold text-[#1b1238]">Start a project ↗</a></Magnetic><a href="/resume" className="inline-flex rounded-full border border-white/15 px-8 py-4 text-sm text-[#cfc3f5]/75">View resume</a></div></div></div><div className="mt-16 border-t border-white/[.09] pt-6"><div className="flex flex-col gap-6 md:flex-row md:items-center md:justify-between"><p className="text-[10px] uppercase tracking-[.24em] text-[#cfc3f5]/28">Brenda Studio · Product Engineering</p><div className="flex flex-wrap gap-6 text-xs text-[#cfc3f5]/42"><a href="https://github.com/brenfreitas29">GitHub ↗</a><a href="https://www.linkedin.com/in/brenda-freitas29">LinkedIn ↗</a><a href="https://www.fiverr.com/brendafreita29">Fiverr ↗</a></div></div></div></div></section>
<footer className="border-t border-white/[.07] bg-[#080512]"><div className="mx-auto flex max-w-[1450px] flex-col gap-3 px-6 py-6 text-[10px] uppercase tracking-[.2em] text-[#cfc3f5]/22 md:flex-row md:items-center md:justify-between md:px-10"><p>© 2026 Brenda Studio</p><p>Remote · Argentina / LATAM</p></div></footer></main>}
