import Image from "next/image";
import Link from "next/link";
import StudioHero from "@/components/StudioHero";
import ProjectCard from "@/components/ProjectCard";

const projects = [
  { number: "01", title: "FlowDesk", category: "CRM / SAAS", description: "A CRM for managing leads, pipeline stages, conversations and follow-ups in one workspace.", tags: ["Next.js", "TypeScript", "Supabase", "Stripe", "RLS"], image: "/projects/flowdesk-dashboard.jpg", href: "/projects/flowdesk", liveUrl: "https://whats-app-crm-system-architecture.vercel.app", codeUrl: "https://github.com/brenfreitas29/FlowDesk" },
  { number: "02", title: "Hair & Skin Clinic", category: "BUSINESS WEBSITE", description: "A multilingual clinic website with clear service discovery and responsive booking journeys.", tags: ["Next.js", "React", "TypeScript", "Responsive UI"], image: "/projects/hair-skin-clinic.png", href: "/projects/hair-skin-clinic", liveUrl: "https://graftclinic.vercel.app", codeUrl: "https://github.com/brenfreitas29/graftclinic" },
  { number: "03", title: "VivaTrip", category: "TRAVEL APP", description: "A travel planning product with authentication, saved trips and pre-travel workflows.", tags: ["Next.js", "TypeScript", "Supabase", "PostgreSQL"], image: "/projects/vivatrip-current.webp", href: "/projects/vivatrip", liveUrl: "https://vivatrip.vercel.app", codeUrl: "https://github.com/brenfreitas29/VivaTrip" },
];

export default function Home() {
  return <main className="br-site">
    <StudioHero />
    <section id="about" className="br-about br-container" aria-labelledby="about-title">
      <div className="br-about-top"><span>01 / ABOUT ME</span><span>BUENOS AIRES · AVAILABLE REMOTELY</span></div>
      <div className="br-about-stage">
        <div className="br-about-visual"><Image src="/brenda-3d-avatar-reference.webp" alt="Retrato ilustrado de Brenda Freitas" fill sizes="(max-width: 800px) 90vw, 40vw" quality={90}/><span className="br-about-visual-caption">BRENDA FREITAS <span>↗</span><small>JUNIOR FULL STACK DEVELOPER</small></span></div>
        <div className="br-about-story"><span className="br-about-intro">HELLO, I&apos;M BRENDA <span aria-hidden="true">✳</span></span><h2 id="about-title">From listening<br/>to <span>building.</span></h2><div className="br-about-copy"><p>I&apos;m a junior full stack developer based in Buenos Aires. I create responsive web experiences with React, Next.js, TypeScript and Supabase.</p><p>My background in customer support taught me to understand the person behind every request. Now I bring that perspective to interfaces, connected systems and the details that make a product useful.</p></div><div className="br-about-actions"><Link href="#work" className="br-about-primary">EXPLORE MY WORK <span aria-hidden="true">↗</span></Link><Link href="/resume" className="br-about-secondary">VIEW RÉSUMÉ ↗</Link></div></div>
      </div>
      <div className="br-about-facts"><div><span>BASED IN</span><strong>BUENOS AIRES, AR</strong></div><div><span>WHAT I BUILD</span><strong>WEB APPS &amp; SAAS</strong></div><div><span>OPEN TO</span><strong>REMOTE JUNIOR ROLES</strong></div></div>
    </section>
    <section id="skills" className="br-services" aria-labelledby="skills-title"><div className="br-container"><div className="br-section-top"><span>02 / WHAT I DO</span><span>DESIGN · DEVELOPMENT · DELIVERY</span></div><div className="br-services-intro"><h2 id="skills-title">Built for people.<br/><span>Built to work.</span></h2><p>I connect the interface and the functionality behind it, turning an idea into a web experience people can actually use.</p></div><div className="br-services-grid"><article><div className="br-service-top"><span>01 / FRONTEND</span><span aria-hidden="true">↗</span></div><h3>Clear<br/>interfaces.</h3><p>Responsive pages and user flows that make it easy to find information and take action.</p><small>REACT · NEXT.JS · TYPESCRIPT</small></article><article><div className="br-service-top"><span>02 / FULL STACK</span><span aria-hidden="true">↗</span></div><h3>Connected<br/>applications.</h3><p>Dashboards, authentication, APIs and data workflows built around practical needs.</p><small>SUPABASE · POSTGRESQL · REST APIS</small></article><article><div className="br-service-top"><span>03 / DELIVERY</span><span aria-hidden="true">↗</span></div><h3>Ready for<br/>real use.</h3><p>From the first working version to deployment, refinement and a smoother experience.</p><small>GIT · VERCEL · PRODUCT THINKING</small></article></div><div className="br-services-end"><span>CURIOUS HOW IT COMES TOGETHER?</span><Link href="#work">EXPLORE SELECTED WORK <span aria-hidden="true">↗</span></Link></div></div></section>
    <section id="work" className="br-work br-container" aria-labelledby="work-title"><div className="br-section-top"><span>03 / SELECTED WORK</span><span>REAL PROJECTS / REAL CODE</span></div><h2 id="work-title">PROJECTS<span>↘</span></h2><div className="br-project-list">{projects.map(project => <ProjectCard key={project.number} project={project}/>)}</div></section>
    <section id="contact" className="br-contact" aria-labelledby="contact-title"><div className="br-container"><div className="br-section-top"><span>04 / GET IN TOUCH</span><span>BUENOS AIRES · AVAILABLE REMOTELY</span></div><div className="br-contact-intro"><div><span className="br-contact-eyebrow"><span aria-hidden="true" className="br-contact-spark">✳</span> HAVE SOMETHING IN MIND?</span><h2 id="contact-title">Let&apos;s build<br/><span>something good.</span></h2></div><p>A website, a useful tool, or a first idea. Tell me what you&apos;re working on and let&apos;s see how I can help.</p></div><div className="br-contact-actions"><div className="br-contact-mail"><span>THE BEST PLACE TO START</span><a href="mailto:brenda.micaela80@gmail.com">brenda.micaela80@gmail.com <span aria-hidden="true">↗</span></a></div><Link href="/start-a-project" className="br-contact-cta">START A PROJECT <span aria-hidden="true">↗</span></Link></div><div className="br-contact-bottom"><span>BRENDA FREITAS / JUNIOR FULL STACK DEVELOPER</span><nav className="br-social" aria-label="Social and résumé links"><a href="https://github.com/brenfreitas29" target="_blank" rel="noopener noreferrer">GITHUB ↗</a><a href="https://www.linkedin.com/in/brenda-freitas29" target="_blank" rel="noopener noreferrer">LINKEDIN ↗</a><Link href="/resume">RÉSUMÉ ↗</Link></nav></div></div></section>
    <footer className="br-footer br-container"><span>© 2026 BRENDA FREITAS</span><span>DESIGNED & BUILT WITH CARE</span><a href="#top">BACK TO TOP ↑</a></footer>
  </main>;
}
