import Image from "next/image";
import Link from "next/link";

type Project = { number:string; title:string; category:string; description:string; tags:string[]; image?:string; href:string; liveUrl?:string; codeUrl?:string; status?:string };

export default function ProjectCard({ project }: { project: Project }) {
  return <article className="br-project">
    <div className="br-project-top"><span className="br-project-number">{project.number}</span><div><span>SELECTED PROJECT / 2026</span><h3>{project.title}</h3></div>{project.status ? <span className="br-project-status"><span aria-hidden="true"/> {project.status}</span> : project.liveUrl && <a href={project.liveUrl} className="br-pill" target="_blank" rel="noopener noreferrer">LIVE PROJECT ↗</a>}</div>
    <div className="br-project-body"><div className="br-project-copy"><p>{project.description}</p><div className="br-project-tags">{project.tags.slice(0,5).map(tag => <span key={tag}>{tag}</span>)}</div><div className="br-project-links"><Link href={project.href}>{project.status ? "PROJECT DETAILS ↗" : "CASE STUDY ↗"}</Link>{project.liveUrl && <a href={project.liveUrl} target="_blank" rel="noopener noreferrer">{project.status ? "VIEW PREVIEW ↗" : "LIVE PROJECT ↗"}</a>}{project.codeUrl && <a href={project.codeUrl} target="_blank" rel="noopener noreferrer">SOURCE CODE ↗</a>}</div></div><div className={`br-project-image${project.image ? "" : " br-project-image-concept"}`}>{project.image ? <Image src={project.image} alt={`${project.title} product interface`} fill quality={90} sizes="(max-width: 800px) 100vw, 62vw" className="object-cover object-top"/> : <div className="br-revilo-preview" aria-label="Editorial preview of the Revilo project in progress"><div className="br-revilo-preview-bar"><span>REVILO.</span><span>HAIR TRANSPLANT · CARE · CONFIDENCE</span></div><div className="br-revilo-preview-hero"><span>THE NEXT CHAPTER<br/>STARTS HERE.</span><div aria-hidden="true" className="br-revilo-orbit">R</div></div><div className="br-revilo-preview-bottom">A DIGITAL EXPERIENCE IN PROGRESS <span>↗</span></div></div>}<div className="br-project-overlay"><span>{project.category}{project.status ? ` / ${project.status}` : ""}</span><div className="br-project-overlay-actions"><Link href={project.href}>PROJECT DETAILS ↗</Link>{project.liveUrl && <a href={project.liveUrl} target="_blank" rel="noopener noreferrer">{project.status ? "PREVIEW ↗" : "LIVE SITE ↗"}</a>}{project.codeUrl && <a href={project.codeUrl} target="_blank" rel="noopener noreferrer">CODE ↗</a>}</div></div></div></div>
  </article>;
}
